Repository yandex-cloud/terraform-provider-yandex, pull requests merged in 2019-10, with the labels that each got.

#24 fix a typo
  website/docs/r/compute_instance.html.markdown
Labels: documentation, size/XS

#25 ForceNew on load_balancer in resource 'yandex_compute_instance_group'
  yandex/resource_yandex_compute_instance_group.go
Labels: size/XS

#26 add instances to resource_yandex_compute_instance_group
  CHANGELOG.md
  website/docs/d/datasource_compute_instance_group.html.markdown
  website/docs/r/compute_instance_group.html.markdown
  yandex/data_source_yandex_compute_instance_group.go
  yandex/data_source_yandex_compute_instance_group_test.go
  yandex/resource_yandex_compute_instance_group.go
  yandex/structures.go
  yandex/structures_test.go
Labels: documentation, size/L
