Repository yandex-cloud/terraform-provider-yandex, pull requests merged in 2020-04, with the labels that each got.

#52 Add variables to instance group.
  CHANGELOG.md
  website/docs/d/datasource_compute_instance_group.html.markdown
  website/docs/r/compute_instance_group.html.markdown
  yandex/data_source_yandex_compute_instance_group.go
  yandex/resource_yandex_compute_instance_group.go
  yandex/resource_yandex_compute_instance_group_test.go
  yandex/structures.go
  yandex/structures_test.go
Labels: documentation, size/XL

#56 add node_ipv4_cidr_mask_size attribute
  CHANGELOG.md
  website/docs/d/datasource_kubernetes_cluster.html.markdown
  website/docs/r/kubernetes_cluster.html.markdown
  yandex/data_source_yandex_kubernetes_cluster.go
  yandex/resource_yandex_kubernetes_cluster.go
  yandex/resource_yandex_kubernetes_cluster_test.go
Labels: documentation, size/M

#60 fix modifying backup_window_start attribute for MySQL Cluster resource
  CHANGELOG.md
  yandex/mdb_mysql_structures.go
  yandex/resource_yandex_mdb_mysql_cluster_test.go
Labels: size/S

#61 Add deploy policy attributes to resource_yandex_kubernetes_node_group
  CHANGELOG.md
  go.mod
  go.sum
  website/docs/d/datasource_kubernetes_node_group.html.markdown
  website/docs/r/kubernetes_node_group.html.markdown
  yandex/data_source_yandex_kubernetes_node_group.go
  yandex/resource_yandex_kubernetes_node_group.go
  yandex/resource_yandex_kubernetes_node_group_test.go
Labels: documentation, size/L

#58 Add fields to ig (sync with public api)
  CHANGELOG.md
  website/docs/d/datasource_compute_instance_group.html.markdown
  website/docs/r/compute_instance_group.html.markdown
  yandex/data_source_yandex_compute_instance_group.go
  yandex/resource_yandex_compute_instance_group.go
  yandex/resource_yandex_compute_instance_group_test.go
  yandex/structures.go
  yandex/structures_test.go
Labels: documentation, size/M

#62 Allow to create k8s cluster with KMS provider.
  CHANGELOG.md
  website/docs/d/datasource_kubernetes_cluster.html.markdown
  website/docs/r/kubernetes_cluster.html.markdown
  yandex/data_source_yandex_kubernetes_cluster.go
  yandex/resource_yandex_kubernetes_cluster.go
  yandex/resource_yandex_kubernetes_cluster_test.go
Labels: documentation, size/M

#63 Add MongoDB Cluster sweeper
  yandex/resource_yandex_mdb_mongodb_cluster_test.go
Labels: size/S

#64 Fix k8s regional cluster tests' resource dependencies
  yandex/resource_yandex_kubernetes_cluster_test.go
Labels: size/XS

#65 added space to fit with terraform documents page
  website/docs/r/vpc_security_group.html.markdown
Labels: documentation, size/XS
