Repository yandex-cloud/terraform-provider-yandex, pull requests merged in 2020-01, with the labels that each got.

#34 remove a duplicated curly brace from the doc
  website/docs/r/mdb_mongodb_cluster.html.markdown
Labels: documentation, size/XS

#37 container optimized image in terraform documentation
  website/docs/e/coi_with_compute_instance.html.markdown
  website/yandex.erb
Labels: documentation, size/L

#41 Website: Fix markdown/link errors in COI examples
  website/docs/e/coi_with_compute_instance.html.markdown
Labels: documentation, size/M
