Repository yandex-cloud/terraform-provider-yandex, pull requests merged in 2020-08, with the labels that each got.

#99 prepare for 42.1 release
  CHANGELOG.md
Labels: size/XS

#96 change sets to lists resource_yandex_mdb_postgresql_cluster and data_source_yandex_mdb_postgresql_cluster
  CHANGELOG.md
  yandex/data_source_yandex_mdb_postgresql_cluster.go
  yandex/data_source_yandex_mdb_postgresql_cluster_test.go
  yandex/mdb_postgresql_structures.go
  yandex/resource_yandex_mdb_postgresql_cluster.go
  yandex/resource_yandex_mdb_postgresql_cluster_test.go
Labels: size/L

#100 KMS symmetric key sweeper for k8s
  yandex/resource_yandex_kms_symmetric_key_test.go
  yandex/resource_yandex_kubernetes_cluster_test.go
  yandex/resource_yandex_kubernetes_node_group_test.go
Labels: size/S

#101 do not recreate autoscaled k8s ngs on min/max size change
  yandex/resource_yandex_kubernetes_node_group.go
Labels: size/XS

#102 Update resourcemanager_cloud_iam_binding.html doc to add Federated users
  website/docs/r/resourcemanager_cloud_iam_binding.html.markdown
Labels: documentation, size/XS
