Repository yandex-cloud/terraform-provider-yandex, pull requests merged in 2020-03, with the labels that each got.

#45 Feature/k8s network policies
  CHANGELOG.md
  website/docs/d/datasource_kubernetes_cluster.html.markdown
  website/docs/r/kubernetes_cluster.html.markdown
  website/docs/r/kubernetes_node_group.html.markdown
  yandex/data_source_yandex_kubernetes_cluster.go
  yandex/data_source_yandex_kubernetes_cluster_test.go
  yandex/resource_yandex_kubernetes_cluster.go
  yandex/resource_yandex_kubernetes_cluster_test.go
Labels: dependencies, documentation, size/M

#47 Add Travis CI
  .golangci.yml
  .travis.yml
  GNUmakefile
  yandex/config_test.go
  yandex/provider_test.go
Labels: size/M

#48 Add k8s sweepers to deps of 'yandex_vpc_subnet'
  yandex/resource_yandex_kubernetes_cluster_test.go
  yandex/resource_yandex_vpc_subnet_test.go
Labels: size/S

#50 make linter happy
  yandex/base_lb_test.go
  yandex/config_test.go
  yandex/data_source_yandex_iam_policy_test.go
  yandex/resource_yandex_compute_disk_test.go
  yandex/resource_yandex_compute_instance_test.go
  yandex/resource_yandex_function_trigger_test.go
  yandex/resource_yandex_mdb_clickhouse_cluster_test.go
  yandex/resource_yandex_resourcemanager_folder_iam_policy_test.go
Labels: size/XS

#49 Implemented yandex_kms_secret_ciphertext resource
  CHANGELOG.md
  website/docs/r/kms_secret_ciphertext.html.markdown
  yandex/provider.go
  yandex/resource_yandex_kms_secret_ciphertext.go
  yandex/resource_yandex_kms_secret_ciphertext_test.go
Labels: documentation, size/L

#53 updated network_acceleration_type spec
  website/docs/r/compute_instance.html.markdown
Labels: documentation, size/XS
